# Form implementation generated from reading ui file 'calendar_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalenderDialog(object):
    def setupUi(self, CalenderDialog):
        CalenderDialog.setObjectName("CalenderDialog")
        CalenderDialog.resize(355, 306)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=CalenderDialog)
        self.calendarWidget.setGeometry(QtCore.QRect(1, 2, 351, 301))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(CalenderDialog)
        QtCore.QMetaObject.connectSlotsByName(CalenderDialog)

    def retranslateUi(self, CalenderDialog):
        _translate = QtCore.QCoreApplication.translate
        CalenderDialog.setWindowTitle(_translate("CalenderDialog", "Dialog"))
